//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekTarifiSitesi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Dbo_YemekTarifiEntities : DbContext
    {
        public Dbo_YemekTarifiEntities()
            : base("name=Dbo_YemekTarifiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBL_GUNUNYEMEGİ> TBL_GUNUNYEMEGİ { get; set; }
        public virtual DbSet<TBL_KATEGORİLER> TBL_KATEGORİLER { get; set; }
        public virtual DbSet<TBL_TARİFLER> TBL_TARİFLER { get; set; }
        public virtual DbSet<TBL_YEMEKLER> TBL_YEMEKLER { get; set; }
        public virtual DbSet<TBL_YORUMLAR> TBL_YORUMLAR { get; set; }
        public virtual DbSet<TBL_YÖNETİCİ> TBL_YÖNETİCİ { get; set; }
        public virtual DbSet<TBL_MESAJLAR> TBL_MESAJLAR { get; set; }
        public virtual DbSet<TBL_HAKKIMIZDA> TBL_HAKKIMIZDA { get; set; }
    }
}
