//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekTarifiSitesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_YEMEKLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_YEMEKLER()
        {
            this.TBL_YORUMLAR = new HashSet<TBL_YORUMLAR>();
        }
    
        public short Yemekid { get; set; }
        public string YemekAd { get; set; }
        public string YemekMalzeme { get; set; }
        public string YemekTarif { get; set; }
        public string YemekResim { get; set; }
        public Nullable<System.DateTime> YemekTarih { get; set; }
        public Nullable<byte> YemekPuan { get; set; }
        public Nullable<short> Kategoriid { get; set; }
    
        public virtual TBL_KATEGORİLER TBL_KATEGORİLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_YORUMLAR> TBL_YORUMLAR { get; set; }
    }
}
