//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekTarifiSitesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_YORUMLAR
    {
        public short Yorumid { get; set; }
        public string YorumAdSoyad { get; set; }
        public string YorumMail { get; set; }
        public Nullable<System.DateTime> YorumTarih { get; set; }
        public Nullable<bool> YorumOnay { get; set; }
        public string Yorumİcerik { get; set; }
        public Nullable<short> Yemekid { get; set; }
    
        public virtual TBL_YEMEKLER TBL_YEMEKLER { get; set; }
    }
}
